extends: "@commercetools-frontend/eslint-config-mc-app"
rules:
  "graphql/template-strings":
    - "error"
    - env: "literal"
  "jest/no-try-expect":
    - "warn"
plugins:
  - "graphql"
settings:
  react:
    version: detect
